# Properties associated with Surface

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX glosis_su: <http://w3id.org/glosis/model/surface/>

SELECT DISTINCT ?parent ?label ?virg1 ?label2 ?label_read ?comment ?virg2 ?definition ?obs
WHERE
{
    ?obs rdfs:subClassOf ?rest1 .
    ?rest1 owl:onProperty sosa:hasFeatureOfInterest ; 
          owl:allValuesFrom glosis_su:GL_Surface .

    ?obs rdfs:subClassOf ?rest2 .
    ?rest2 owl:onProperty sosa:observedProperty ; 
           owl:hasValue ?prop .

    ?prop rdfs:label ?label ;
          rdfs:comment ?comment ;
          skos:definition ?definition .

    BIND ("Surface" AS ?parent)
    BIND (?label AS ?label2)
    BIND (CONCAT(UCASE(SUBSTR(?label, 1, 1)), SUBSTR(REPLACE(?label, "([A-Z])", " $1"), 2))  AS ?label_read)
    BIND ("," AS ?virg1)
    BIND (",,," AS ?virg2)
}

# Properties associated with Profile

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX glosis_pr: <http://w3id.org/glosis/model/profile/>

SELECT DISTINCT ?parent ?label ?virg1 ?label2 ?label_read ?comment ?virg2 ?definition ?obs
WHERE
{
    ?obs rdfs:subClassOf ?rest1 .
    ?rest1 owl:onProperty sosa:hasFeatureOfInterest ; 
          owl:allValuesFrom glosis_pr:GL_Profile .

    ?obs rdfs:subClassOf ?rest2 .
    ?rest2 owl:onProperty sosa:observedProperty ; 
           owl:hasValue ?prop .

    ?prop rdfs:label ?label ;
          rdfs:comment ?comment ;
          skos:definition ?definition .

    BIND ("Profile" AS ?parent)
    BIND (?label AS ?label2)
    BIND (CONCAT(UCASE(SUBSTR(?label, 1, 1)), SUBSTR(REPLACE(?label, "([A-Z])", " $1"), 2))  AS ?label_read)
    BIND ("," AS ?virg1)
    BIND (",,," AS ?virg2)
}



# Properties associated with Plot/Site

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX glosis_sp: <http://w3id.org/glosis/model/siteplot/>

SELECT DISTINCT ?parent ?label ?virg1 ?label2 ?label_read ?comment ?virg2 ?definition ?obs
WHERE
{
    ?obs rdfs:subClassOf ?rest1 .
    ?rest1 owl:onProperty sosa:hasFeatureOfInterest ; 
           owl:allValuesFrom [owl:unionOf (glosis_sp:GL_Plot glosis_sp:GL_Site) ] .

    ?obs rdfs:subClassOf ?rest2 .
    ?rest2 owl:onProperty sosa:observedProperty ; 
           owl:hasValue ?prop .

    ?prop rdfs:label ?label ;
          rdfs:comment ?comment ;
          skos:definition ?definition .
    
    BIND ("Plot-Site" AS ?parent)
    BIND (?label AS ?label2)
    BIND (CONCAT(UCASE(SUBSTR(?label, 1, 1)), SUBSTR(REPLACE(?label, "([A-Z])", " $1"), 2))  AS ?label_read)
    BIND ("," AS ?virg1)
    BIND (",,," AS ?virg2)
}

# Properties associated with Layer/Horizon

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX glosis_lh: <http://w3id.org/glosis/model/layerhorizon/>

SELECT DISTINCT ?parent ?label ?virg1 ?label2 ?label_read ?comment ?virg2 ?definition ?obs
WHERE
{
    ?obs rdfs:subClassOf ?rest1 .
    ?rest1 owl:onProperty sosa:hasFeatureOfInterest ; 
           owl:allValuesFrom [owl:unionOf (glosis_lh:GL_Layer glosis_lh:GL_Horizon) ] .

    ?obs rdfs:subClassOf ?rest2 .
    ?rest2 owl:onProperty sosa:observedProperty ; 
           owl:hasValue ?prop .

    ?prop rdfs:label ?label ;
          rdfs:comment ?comment ;
          skos:definition ?definition .

    BIND ("Surface" AS ?parent)
    BIND (?label AS ?label2)
    BIND (CONCAT(UCASE(SUBSTR(?label, 1, 1)), SUBSTR(REPLACE(?label, "([A-Z])", " $1"), 2))  AS ?label_read)
    BIND ("," AS ?virg1)
    BIND (",,," AS ?virg2)
}
