PREFIX sosa: <http://www.w3.org/ns/sosa/>

SELECT DISTINCT ?uri ?label_list ?label ?comment ?definition
WHERE
{
  ?uri a sosa:ObservableProperty ;
     rdfs:label ?label ;
     rdfs:comment ?comment ;
     skos:definition ?definition .
  ?obs rdfs:subClassOf ?restriction .
  ?restriction a owl:Restriction ;
      owl:onProperty sosa:hasFeatureOfInterest ;
      owl:allValuesFrom ?foi .
  ?foi owl:unionOf ?list .
  ?list rdf:first ?foi_first .
  ?foi_first rdfs:label ?label_list .
}
ORDER BY ?uri


PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX owl:   <http://www.w3.org/2002/07/owl#> 
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX glosis_pr: <http://w3id.org/glosis/model/profile/> 

SELECT DISTINCT ?prop ?label ?comment ?definition
WHERE
{
  ?prop a sosa:ObservableProperty ;
     rdfs:label ?label ;
     rdfs:comment ?comment ;
     skos:definition ?definition .
  ?obs a sosa:Observation .
  ?obs rdfs:subClassOf ?rest_prop .
  ?obs rdfs:subClassOf ?rest_foi .
  ?rest_prop a owl:Restriction ;
      owl:onProperty sosa:observedProperty ;
      owl:hasValue ?prop .
  ?rest_foi a owl:Restriction ;
      owl:onProperty sosa:hasFeatureOfInterest ;
      owl:allValuesFrom glosis_pr:GL_Profile .
}
ORDER BY ?prop


PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX owl:   <http://www.w3.org/2002/07/owl#> 
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX glosis_pr: <http://w3id.org/glosis/model/profile/> 

SELECT DISTINCT ?uri ?label ?comment ?definition ?foi
WHERE
{
  ?uri a sosa:ObservableProperty ;
     rdfs:label ?label ;
     rdfs:comment ?comment ;
     skos:definition ?definition .
  ?obs rdfs:subClassOf ?restriction .
  ?restriction a owl:Restriction ;
      owl:onProperty sosa:hasFeatureOfInterest ;
      owl:allValuesFrom ?foi .
}
ORDER BY ?uri



